import Foundation

/// Filesystem layout for the embedded herdr runtime.
///
/// Everything lives under one root so the prototype cannot touch the
/// developer's real herdr session, its config, or its persisted state.
public struct RuntimePaths: Sendable {
    public let root: URL

    public init(root: URL) {
        self.root = root
    }

    /// Default location: `~/Library/Application Support/<bundle id>/runtime`.
    public static func defaultLocation(
        bundleIdentifier: String = "app.herda"
    ) -> RuntimePaths {
        let support = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)
            .first ?? URL(fileURLWithPath: NSHomeDirectory() + "/Library/Application Support")
        return RuntimePaths(
            root: support
                .appendingPathComponent(bundleIdentifier, isDirectory: true)
                .appendingPathComponent("runtime", isDirectory: true)
        )
    }

    public var configHome: URL { root.appendingPathComponent("config", isDirectory: true) }
    public var stateHome: URL { root.appendingPathComponent("state", isDirectory: true) }

    /// herdr's `config_dir()` appends "herdr" to `XDG_CONFIG_HOME`.
    public var configFile: URL {
        configHome
            .appendingPathComponent("herdr", isDirectory: true)
            .appendingPathComponent("config.toml")
    }

    public var apiSocket: URL { root.appendingPathComponent("herdr.sock") }

    /// herdr derives this from the API socket by inserting "-client" before
    /// the extension, so it must not be set independently.
    public var clientSocket: URL { root.appendingPathComponent("herdr-client.sock") }

    /// Hides herdr's own sidebar from the first frame, since the native UI
    /// replaces it, and sets `[theme] name` so herdr's own chrome — hidden in
    /// this prototype, but consulted if it ever becomes visible again — matches
    /// whatever the client's own UI is themed as.
    public func configContents(themeName: String) -> String {
        // `onboarding = false` must come first: it is a top-level TOML key, and
        // it is essential rather than cosmetic. With onboarding active the
        // server sits in `Mode::Onboarding`, which covers the terminal with a
        // first-run overlay the prototype cannot dismiss.
        //
        // `sidebar_start_collapsed = true` with the `hidden` mode makes herdr's
        // own sidebar invisible from the first frame. This is deliberately not a
        // runtime toggle: a one-shot keypress after the first frame is fragile,
        // because workspace operations re-expand the sidebar server-side and it
        // reappears. Starting collapsed holds regardless of later state.
        //
        // `hide_tab_bar_when_single_tab = true` drops the character-drawn tab
        // row, which listed the same workspaces the native sidebar now does. The
        // row returns as soon as a workspace has a second tab — tabs are still
        // herdr's to draw, and the native UI does not show them.
        """
        # Generated by Herda. Do not edit; it is rewritten on launch.
        onboarding = false

        [ui]
        sidebar_start_collapsed = true
        sidebar_collapsed_mode = "hidden"
        hide_tab_bar_when_single_tab = true

        [theme]
        name = "\(themeName)"
        """
    }

    public func createDirectories() throws {
        for directory in [root, configHome, stateHome, configFile.deletingLastPathComponent()] {
            try FileManager.default.createDirectory(
                at: directory,
                withIntermediateDirectories: true
            )
        }
    }

    public func writeConfig(themeName: String) throws {
        try createDirectories()
        try configContents(themeName: themeName).write(to: configFile, atomically: true, encoding: .utf8)
    }

    /// Reads the `[theme] name` from a config.toml written by a previous
    /// launch, if one exists — the "combine both" half of theme sync: this
    /// lets a fresh launch continue with whatever theme was last selected,
    /// before `writeConfig` overwrites the file.
    public func existingThemeName() -> String? {
        guard let data = try? Data(contentsOf: configFile),
              let text = String(data: data, encoding: .utf8)
        else { return nil }
        return Theme.name(fromConfig: text)
    }

    /// Builds the child environment. Inherited `HERDR_*` variables are removed
    /// first: the app may itself have been launched from inside a herdr
    /// session, and those would redirect the child at the real server.
    public func environment(basedOn parent: [String: String]) -> [String: String] {
        var env = parent
        for key in env.keys where key.hasPrefix("HERDR_") {
            env.removeValue(forKey: key)
        }
        env["HERDR_SOCKET_PATH"] = apiSocket.path
        env["XDG_CONFIG_HOME"] = configHome.path
        env["XDG_STATE_HOME"] = stateHome.path
        return env
    }
}
