import Foundation

/// Filesystem layout for the embedded herdr runtime.
///
/// Everything lives under one root so the prototype cannot touch the
/// developer's real herdr session, its config, or its persisted state.
public struct RuntimePaths: Sendable {
    public let root: URL

    public init(root: URL) {
        self.root = root
    }

    /// Default location: `~/Library/Application Support/<bundle id>/runtime`.
    public static func defaultLocation(
        bundleIdentifier: String = "dev.herdr.macos-client-prototype"
    ) -> RuntimePaths {
        let support = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)
            .first ?? URL(fileURLWithPath: NSHomeDirectory() + "/Library/Application Support")
        return RuntimePaths(
            root: support
                .appendingPathComponent(bundleIdentifier, isDirectory: true)
                .appendingPathComponent("runtime", isDirectory: true)
        )
    }

    public var configHome: URL { root.appendingPathComponent("config", isDirectory: true) }
    public var stateHome: URL { root.appendingPathComponent("state", isDirectory: true) }

    /// herdr's `config_dir()` appends "herdr" to `XDG_CONFIG_HOME`.
    public var configFile: URL {
        configHome
            .appendingPathComponent("herdr", isDirectory: true)
            .appendingPathComponent("config.toml")
    }

    public var apiSocket: URL { root.appendingPathComponent("herdr.sock") }

    /// herdr derives this from the API socket by inserting "-client" before
    /// the extension, so it must not be set independently.
    public var clientSocket: URL { root.appendingPathComponent("herdr-client.sock") }

    /// Hides herdr's own sidebar from the first frame, since the native UI
    /// replaces it.
    public var configContents: String {
        // `onboarding = false` must come first: it is a top-level TOML key, and
        // it is essential rather than cosmetic. With onboarding active the
        // server sits in `Mode::Onboarding`, which covers the terminal with a
        // first-run overlay the prototype cannot dismiss.
        //
        // `sidebar_start_collapsed = true` with the `hidden` mode makes herdr's
        // own sidebar invisible from the first frame. This is deliberately not a
        // runtime toggle: a one-shot keypress after the first frame is fragile,
        // because workspace operations re-expand the sidebar server-side and it
        // reappears. Starting collapsed holds regardless of later state.
        """
        # Generated by HerdrPrototype. Do not edit; it is rewritten on launch.
        onboarding = false

        [ui]
        sidebar_start_collapsed = true
        sidebar_collapsed_mode = "hidden"
        """
    }

    public func createDirectories() throws {
        for directory in [root, configHome, stateHome, configFile.deletingLastPathComponent()] {
            try FileManager.default.createDirectory(
                at: directory,
                withIntermediateDirectories: true
            )
        }
    }

    public func writeConfig() throws {
        try createDirectories()
        try configContents.write(to: configFile, atomically: true, encoding: .utf8)
    }

    /// Builds the child environment. Inherited `HERDR_*` variables are removed
    /// first: the app may itself have been launched from inside a herdr
    /// session, and those would redirect the child at the real server.
    public func environment(basedOn parent: [String: String]) -> [String: String] {
        var env = parent
        for key in env.keys where key.hasPrefix("HERDR_") {
            env.removeValue(forKey: key)
        }
        env["HERDR_SOCKET_PATH"] = apiSocket.path
        env["XDG_CONFIG_HOME"] = configHome.path
        env["XDG_STATE_HOME"] = stateHome.path
        return env
    }
}
